### ISSUE TITLE
Кампании Nod's Revolution, Revenge of the Forgotten и другие работы их авторов плохо совместимы с Tiberium Essence 2

### ISSUE THREAD

**Issue by OcularisI** [MahBoiTranslator/TiberiumEssenceRu#3]
Кампания Nod's Revolution (https://www.moddb.com/addons/nods-revolution)
Кампания Revenge of the Forgotten (https://www.moddb.com/games/cc-tiberium-wars/addons/revenge-of-the-forgotten)
И другие работы их авторов (TheFinnishGuy, playmbsk) для Tiberium Essence делались 
под версию 1.4, не считая сломанный баланс, они имеют серьёзные проблемы с проходимостью, из за ошибок на версии Tiberium Essence 2.
Например в Revenge of the Forgotten не появляются войска ракетчиков у мутантов, а без них миссии по сути не проходимы.
В Nod's Revolution аналогично нарушен баланс, сломан ИИ спавна войск, и хищной фауны.
Возможно эти проблемы наблюдались только у меня, но скорее всего они связаны с разностью версий.

**Comment by MahBoiTranslator** [comment]
Эти баги повторяться повторяться на любой версии TE 2.0. Некоторые кампании я правил, чтобы они проходились. Например Nod's Revolution я исправлял во многих местах, но одну из миссий кампаний точно сейчас нельзя пройти. Был бы крайне благодарен, если бы ты, @OcularisI, указал номера/названия душных и непроходимых миссий, чтобы я их поправил к следующему релизу.

**Comment by MahBoiTranslator** [comment]
4-ая миссия Nod's Revolution исправлена коммитом [e50898f](https://github.com/MahBoiTranslator/TiberiumEssenceRu/commit/e50898fb4bf432f06783409aa19097de1f9c9133)

**Comment by MahBoiTranslator** [comment]
По кампании [Revenge of the Forgotten](https://www.moddb.com/games/cc-tiberium-wars/addons/revenge-of-the-forgotten):
* 1-ую миссию исправил — её там никак нельзя было пройти. Заменил 2 отряда Мародёров на Призрака и Умагон.
* 2-ую миссию и без каких-либо правок можно было пройти, однако решил упростить её чутка, добавив Умагон.
![image](https://user-images.githubusercontent.com/56169197/229594771-c92e29cc-74d1-4a8d-a697-a89ba6105472.png)
* 3-ья миссия проходима без каких-либо правок
* 4-ая миссия тоже проходима без каких-либо правок
* 5-ая миссия — пару сохранений и пройдена
